import {renderMarkdown} from './markdown.mjs';
export function messageTime(value) {
 const d=new Date(value);
 if(!value || !Number.isFinite(d.getTime()) || d.getFullYear()<1970)return '时间未知';
 return new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d);
}
export function setTime(node,value){node.textContent=messageTime(value);if(node.textContent!=='时间未知'){node.dateTime=value;node.title=value+' · 按本机时区显示';}else{node.removeAttribute('datetime');node.title='历史记录未保存有效时间';}}
const states={todo:'待处理',queued:'排队中',running:'处理中',needs_confirmation:'需要确认',review:'待验收',blocked:'已中断 / 异常',completed:'已完成'};
export function setupTasks({getState,changeView,saveDraft}) {
 const panel=document.getElementById('tasks-panel'),list=document.getElementById('task-list'),detail=document.getElementById('task-detail'),status=document.getElementById('task-status');
 const dialog=document.getElementById('convert-task'),create=document.getElementById('create-task'),title=document.getElementById('task-title'),criteria=document.getElementById('task-acceptance');
 const follow=document.getElementById('task-followup'),text=document.getElementById('task-text'),send=document.getElementById('task-send');
 let listSignature='',roleSignature='',loading=false;
 let selected=0,visible=false,generation=0,busy=false,task=null,signature='',before=0,listMore=false,runMore=false,runBefore=0,actionAttempt=null,convertAttempt=null,drafts={},restored=false;
 const writer=()=>getState()?.userRole==='roommate';
 const id=()=>crypto.randomUUID().replaceAll('-','');
 const button=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b;};
 const line=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;};
 async function request(url,body){const r=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(!r.ok)throw new Error(await r.text());return r.json();}
 function notice(err){status.textContent=err.message || err;}
 function drawList(tasks,append=false){if(!append)list.replaceChildren();for(const t of tasks || []){const b=button('T-'+t.number+' · '+t.title+' · '+(states[t.state]||t.state),()=>open(t.id));b.className='task-list-item';b.setAttribute('aria-pressed',String(t.id===selected));list.append(b);}if(!list.children.length)list.append(line('p','还没有项目任务。在主聊天中选择一条消息，点击“转为任务”。'));}
 function drawRuns(runs,append=false){const root=document.getElementById('task-runs');if(!append)root.replaceChildren();for(const r of runs || []){const article=document.createElement('article');article.append(line('h4','执行记录 · '+({completed:'执行结束，等待验收',failed:'失败或中断',queued:'排队中',running:'处理中',interrupted:'已中断','needs-review':'需要确认',dispatching:'正在提交'}[r.state]||r.state)));const time=document.createElement('time');setTime(time,r.createdAt);article.append(time,line('p',r.text));for(const a of r.answers || []){const time=document.createElement('time');setTime(time,a.time);const body=document.createElement('div');renderMarkdown(body,a.text);article.append(time,body);}root.append(article);}runBefore=runs?.at(-1)?.messageId || 0;document.getElementById('task-runs-more').hidden=!runMore;}
 function drawTask(t,more){task=t;runMore=more;detail.hidden=false;document.getElementById('task-heading').textContent='T-'+t.number+' · '+t.title;document.getElementById('task-state').textContent=states[t.state]||t.state;document.getElementById('task-dates').textContent='创建 '+messageTime(t.createdAt)+(t.completedAt?' · '+t.completedBy+' 标记完成于 '+messageTime(t.completedAt):'');document.getElementById('task-criteria').textContent=t.acceptance || '未填写验收标准';document.getElementById('task-source').textContent=t.sourceText || '';document.getElementById('task-source-seq').textContent='来源消息 #'+t.sourceSeq+' · '+t.sourceClientId;
 const actions=document.getElementById('task-actions');actions.replaceChildren();if(writer()){if(t.state==='completed')actions.append(button('重新打开任务',()=>mutate('reopen')));else{const b=button('标记任务完成',()=>mutate('complete'));b.disabled=!['review','todo'].includes(t.state);b.title=b.disabled?'请等待执行结束并处理异常后再验收':'确认结果符合验收标准后标记完成';actions.append(b);}}
 follow.hidden=!writer();send.disabled=busy || !getState()?.connected || ['completed','queued','running','needs_confirmation'].includes(t.state);text.disabled=busy;document.getElementById('task-followup-hint').textContent=t.state==='completed'?'需要补充工作时，请先重新打开任务。':'发送后沿用本项目模型会话，进入共享执行队列。查看其他任务不会改变执行目标。';
 drawRuns(t.runs);const history=document.getElementById('task-history');history.replaceChildren();for(const c of t.history || [])history.append(line('li',messageTime(c.time)+' · '+c.actor+' · '+({created:'转为任务',complete:'标记完成',reopen:'重新打开',run_added:'追加执行'}[c.action]||c.action)+(c.note?' · '+c.note:'')));
 }
 async function refresh(){if(!visible||busy||loading)return;loading=true;const g=generation;try{const result=await request('tasks');if(g!==generation)return;const ls=JSON.stringify(result);if(ls!==listSignature){listSignature=ls;drawList(result.tasks);before=result.tasks?.at(-1)?.id || 0;listMore=result.more;document.getElementById('tasks-more').hidden=!listMore;}if(selected){const result=await request('tasks?id='+selected);if(g!==generation)return;const next=JSON.stringify([result,getState()?.userRole,getState()?.connected]);if(next!==signature){signature=next;drawTask(result.task,result.more);}}}catch(e){if(g===generation)notice(e);}finally{loading=false;if(g!==generation && visible && !busy)queueMicrotask(refresh);}}
 function stash(){if(!selected)return;drafts[selected]={...(drafts[selected]||{}),text:text.value};saveDraft();}
 async function open(taskId){if(busy)return;stash();selected=taskId;generation++;signature='';listSignature='';detail.hidden=true;text.value=drafts[selected]?.text || '';actionAttempt=null;show(true);await refresh();}
 function show(value){visible=value;panel.hidden=!value;if(!value){generation++;return;}changeView();refresh();}
 async function mutate(action){if(busy||!task||!writer())return;const body={action,taskId:task.id,expectedRevision:task.revision};if(!actionAttempt || JSON.stringify(actionAttempt.body)!==JSON.stringify(body))actionAttempt={body,request:{...body,requestId:id()}};busy=true;generation++;status.textContent='正在保存…';try{await request('tasks',actionAttempt.request);actionAttempt=null;notice(action==='complete'?'任务已完成':'任务已重新打开');}catch(e){notice(e);}finally{busy=false;signature='';await refresh();}}
 create.onsubmit=async e=>{e.preventDefault();if(busy||!writer())return;const body={action:'convert',sourceSeq:Number(dialog.dataset.seq),title:title.value.trim(),acceptance:criteria.value.trim()};if(!convertAttempt||JSON.stringify(convertAttempt.body)!==JSON.stringify(body))convertAttempt={body,request:{...body,requestId:id()}};busy=true;create.querySelector('button[type=submit]').disabled=true;try{const r=await request('tasks',convertAttempt.request);dialog.close();convertAttempt=null;busy=false;await open(r.task.id);notice('已转为任务。来源消息保留，模型不会重复执行。');}catch(e){document.getElementById('task-create-status').textContent=e.message;}finally{busy=false;create.querySelector('button[type=submit]').disabled=false;}};
 document.getElementById('task-create-cancel').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 follow.onsubmit=async e=>{e.preventDefault();if(busy||send.disabled||!selected||!text.value.trim())return;stash();const taskId=selected;let draft=drafts[taskId];if(!draft.attempt||draft.attempt.text!==text.value.trim())draft.attempt={id:id(),taskId,text:text.value.trim()};saveDraft();busy=true;generation++;send.disabled=true;text.disabled=true;notice('正在提交任务补充…');try{await request('submit',draft.attempt);drafts[taskId]={text:''};text.value='';saveDraft();notice('已提交到此任务。');}catch(e){notice(e);}finally{busy=false;text.disabled=false;signature='';await refresh();}};
 text.oninput=stash;text.onkeydown=e=>{if(e.key==='Enter'&&!e.altKey&&!e.isComposing){e.preventDefault();follow.requestSubmit();}};
 document.getElementById('tasks-refresh').onclick=()=>{signature='';refresh();};
 document.getElementById('tasks-more').onclick=async()=>{const g=generation;try{const r=await request('tasks?before='+before);if(g!==generation)return;drawList(r.tasks,true);before=r.tasks?.at(-1)?.id||0;document.getElementById('tasks-more').hidden=!r.more;}catch(e){notice(e);}};
 document.getElementById('task-runs-more').onclick=async()=>{const g=generation;try{const r=await request('tasks?id='+selected+'&before='+runBefore);if(g!==generation)return;runMore=r.more;drawRuns(r.task.runs,true);}catch(e){notice(e);}};
 setInterval(refresh,4000);
 return {show,refresh,isVisible:()=>visible,draft:()=>structuredClone(drafts),restore(value){if(!restored){drafts=value && typeof value==='object'?value:{};restored=true;}},convert(answer){if(!writer())return;dialog.dataset.seq=answer.seq;title.value=(answer.text || '').split('\n').find(s=>s.trim())?.slice(0,60)||'项目任务';criteria.value='';document.getElementById('task-create-status').textContent='只建立任务与来源的关联，不会再次执行这条消息。';convertAttempt=null;dialog.showModal();},updateRole(){document.querySelectorAll('.convert-task').forEach(b=>b.hidden=!writer()||!b.dataset.seq);const rs=JSON.stringify([getState()?.userRole,getState()?.connected]);if(task&&rs!==roleSignature){roleSignature=rs;drawTask(task,runMore);}}};
}
